esphome:
  name: my-proj

esp8266:
  board: d1_mini_pro
  framework:
    version: recommended
  restore_from_flash: true

wifi:
  fast_connect: True
  use_address: !secret use_address
  domain: !secret domain
  min_auth_mode: WPA2
  manual_ip:
    static_ip: !secret use_address
    gateway: !secret gateway
    subnet:  !secret subnet
    dns1:    !secret dns1
  ap:
    ssid:     my-ap
    password: !secret ap_password
    channel:  1

  networks:
    - ssid:     !secret wifi_ssid_NoT
      password: !secret wifi_password_NoT

logger:
  level: DEBUG
  logs:
    mqtt.component: ERROR
    mqtt.client: ERROR
    wifi: ERROR
    wifi_info: ERROR
    wifi_signal: ERROR
    wifi_signal.sensor: ERROR
    template.number: ERROR
    template.text_sensor: ERROR
    uptime.sensor: ERROR
    restart.button: ERROR
    safe_mode.button: ERROR 
    version.text_sensor: ERROR
    safe_mode: ERROR
    logger: ERROR
    esp8266_pwm: ERROR
    light: ERROR
    esphome.ota: ERROR
    mdns: ERROR
    homeassistant.binary_sensor: ERROR
    api: ERROR
    status: ERROR
    time: ERROR
    text_sensor: ERROR
    sensor: ERROR
    api.service: ERROR
    api.connection: ERROR

api:
  port: 6053
  id: api_server
  encryption:
    key: !secret api_key
  reboot_timeout: 5min

###################################################################
# https://esphome.io/components/ota.html
###################################################################
ota:
  - platform: esphome
    password: !secret ota_password
    port: 8266

external_components:
  # - source: github://JayElDubya/esphome_ds24xx_component@master
  #   components: [ ds24xx ]

  - source:
      type: local
      path: ../components
      # components: [ ds24xx ]

one_wire:
  - platform: gpio
    id: ow_bus
    pin: 13

ds24xx:
  id: ds1
  one_wire: ow_bus
  inverted: false
  outputs:
    - id: o0
      channel: 0
      device_index: 0
      inverted: false
    - id: o1
      channel: 1
      device_index: 0
      inverted: false

output:
  - platform: esp8266_pwm
    id: indicator_output
    pin: D4
    inverted: true


switch:
  - platform: output
    name: "Generic Output 0"
    output: o0
    id: switch_fan
    internal: true

  - platform: output
    name: "Generic Output 1"
    output: o1
    id: switch_fire
    internal: true

  - name: "Fireplace Fan"
    platform: template
    id: fan
    icon: mdi:fan
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - switch.turn_on:
          id: switch_fan
      - switch.template.publish:
          id: fan
          state: ON
    turn_off_action:
      - switch.turn_off:
          id: switch_fan
      - switch.template.publish:
          id: fan
          state: OFF
    lambda: "return id(fan).state;"

  - name: "Fireplace Fire"
    platform: template
    id: fire
    icon: mdi:fire
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - switch.turn_on:
          id: switch_fire
      - switch.template.publish:
          id: fire
          state: ON
    turn_off_action:
      - switch.turn_off:
          id: switch_fire
      - switch.template.publish:
          id: fire
          state: OFF
    lambda: "return id(fire).state;"


light:
  - platform: monochromatic
    name: "Indicator"
    id: indicator
    output: indicator_output
    restore_mode: ALWAYS_OFF
    default_transition_length: 0ms
    internal: true